In [1]:
import requests
import json
import pandas as pd

In [2]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": [
    'LNS11000000', 'LNS12000000', 'LNS13000000', 'LNS14000000', 'CES0500000002', 'CES0500000003'
    ]
        ,"startyear":"2012", "endyear":"2022", "registrationkey": "6a4fc3836e344229b9fe9dc5925c842e",
       "catalog": "true",})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)

In [7]:
json_data['Results']['series'][3]['catalog']

{'series_title': '(Seas) Unemployment Rate',
 'series_id': 'LNS14000000',
 'seasonality': 'Seasonally Adjusted',
 'survey_name': 'Labor Force Statistics from the Current Population Survey',
 'survey_abbreviation': 'LN',
 'measure_data_type': 'Percent or rate',
 'commerce_industry': 'All Industries',
 'occupation': 'All Occupations',
 'cps_labor_force_status': 'Unemployment rate',
 'demographic_age': '16 years and over',
 'demographic_ethnic_origin': 'All Origins',
 'demographic_race': 'All Races',
 'demographic_gender': 'Both Sexes',
 'demographic_education': 'All educational levels'}

In [4]:
json_data['Results']['series'][0]['data']

[{'year': '2022',
  'period': 'M12',
  'periodName': 'December',
  'latest': 'true',
  'value': '164966',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M11',
  'periodName': 'November',
  'value': '164527',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M10',
  'periodName': 'October',
  'value': '164646',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M09',
  'periodName': 'September',
  'value': '164619',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M08',
  'periodName': 'August',
  'value': '164714',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M07',
  'periodName': 'July',
  'value': '163990',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M06',
  'periodName': 'June',
  'value': '164002',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M05',
  'periodName': 'May',
  'value': '164278',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M04',
  'periodName': 'April',
  'value': '163950',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M03',
  'periodName': 'March',
  'value': '164301',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M02',
  'periodName': 'February',
  'value': '163862',
  'footnotes': [{}]},
 {'year': '2022',
  'period': 'M01',
  'periodName': 'January',
  'value': '163633',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2021',
  'period': 'M12',
  'periodName': 'December',
  'value': '162410',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M11',
  'periodName': 'November',
  'value': '162315',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M10',
  'periodName': 'October',
  'value': '161740',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M09',
  'periodName': 'September',
  'value': '161544',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M08',
  'periodName': 'August',
  'value': '161535',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M07',
  'periodName': 'July',
  'value': '161486',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M06',
  'periodName': 'June',
  'value': '161192',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M05',
  'periodName': 'May',
  'value': '160740',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M04',
  'periodName': 'April',
  'value': '160908',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M03',
  'periodName': 'March',
  'value': '160463',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M02',
  'periodName': 'February',
  'value': '160187',
  'footnotes': [{}]},
 {'year': '2021',
  'period': 'M01',
  'periodName': 'January',
  'value': '160025',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2020',
  'period': 'M12',
  'periodName': 'December',
  'value': '160757',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M11',
  'periodName': 'November',
  'value': '160687',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M10',
  'periodName': 'October',
  'value': '160944',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M09',
  'periodName': 'September',
  'value': '160224',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M08',
  'periodName': 'August',
  'value': '160722',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M07',
  'periodName': 'July',
  'value': '160102',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M06',
  'periodName': 'June',
  'value': '159900',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M05',
  'periodName': 'May',
  'value': '158067',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M04',
  'periodName': 'April',
  'value': '156308',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M03',
  'periodName': 'March',
  'value': '162635',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M02',
  'periodName': 'February',
  'value': '164458',
  'footnotes': [{}]},
 {'year': '2020',
  'period': 'M01',
  'periodName': 'January',
  'value': '164348',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2019',
  'period': 'M12',
  'periodName': 'December',
  'value': '164704',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M11',
  'periodName': 'November',
  'value': '164553',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M10',
  'periodName': 'October',
  'value': '164432',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M09',
  'periodName': 'September',
  'value': '164077',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M08',
  'periodName': 'August',
  'value': '163763',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M07',
  'periodName': 'July',
  'value': '163533',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M06',
  'periodName': 'June',
  'value': '163073',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M05',
  'periodName': 'May',
  'value': '162756',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M04',
  'periodName': 'April',
  'value': '162594',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M03',
  'periodName': 'March',
  'value': '162937',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M02',
  'periodName': 'February',
  'value': '163023',
  'footnotes': [{}]},
 {'year': '2019',
  'period': 'M01',
  'periodName': 'January',
  'value': '162968',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2018',
  'period': 'M12',
  'periodName': 'December',
  'value': '163206',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M11',
  'periodName': 'November',
  'value': '162836',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M10',
  'periodName': 'October',
  'value': '162602',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M09',
  'periodName': 'September',
  'value': '162087',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M08',
  'periodName': 'August',
  'value': '161660',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M07',
  'periodName': 'July',
  'value': '162341',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M06',
  'periodName': 'June',
  'value': '162210',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M05',
  'periodName': 'May',
  'value': '161848',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M04',
  'periodName': 'April',
  'value': '161771',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M03',
  'periodName': 'March',
  'value': '161686',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M02',
  'periodName': 'February',
  'value': '161778',
  'footnotes': [{}]},
 {'year': '2018',
  'period': 'M01',
  'periodName': 'January',
  'value': '160914',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2017',
  'period': 'M12',
  'periodName': 'December',
  'value': '160535',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M11',
  'periodName': 'November',
  'value': '160579',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M10',
  'periodName': 'October',
  'value': '160309',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M09',
  'periodName': 'September',
  'value': '161140',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M08',
  'periodName': 'August',
  'value': '160586',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M07',
  'periodName': 'July',
  'value': '160462',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M06',
  'periodName': 'June',
  'value': '160192',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M05',
  'periodName': 'May',
  'value': '160068',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M04',
  'periodName': 'April',
  'value': '160345',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M03',
  'periodName': 'March',
  'value': '160137',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M02',
  'periodName': 'February',
  'value': '159859',
  'footnotes': [{}]},
 {'year': '2017',
  'period': 'M01',
  'periodName': 'January',
  'value': '159620',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2016',
  'period': 'M12',
  'periodName': 'December',
  'value': '159678',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M11',
  'periodName': 'November',
  'value': '159506',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M10',
  'periodName': 'October',
  'value': '159605',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M09',
  'periodName': 'September',
  'value': '159714',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M08',
  'periodName': 'August',
  'value': '159562',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M07',
  'periodName': 'July',
  'value': '159194',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M06',
  'periodName': 'June',
  'value': '158967',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M05',
  'periodName': 'May',
  'value': '158784',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M04',
  'periodName': 'April',
  'value': '159141',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M03',
  'periodName': 'March',
  'value': '159179',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M02',
  'periodName': 'February',
  'value': '158640',
  'footnotes': [{}]},
 {'year': '2016',
  'period': 'M01',
  'periodName': 'January',
  'value': '158280',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2015',
  'period': 'M12',
  'periodName': 'December',
  'value': '158035',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M11',
  'periodName': 'November',
  'value': '157463',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M10',
  'periodName': 'October',
  'value': '157167',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M09',
  'periodName': 'September',
  'value': '156733',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M08',
  'periodName': 'August',
  'value': '157172',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M07',
  'periodName': 'July',
  'value': '156997',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M06',
  'periodName': 'June',
  'value': '157062',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M05',
  'periodName': 'May',
  'value': '157651',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M04',
  'periodName': 'April',
  'value': '157060',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M03',
  'periodName': 'March',
  'value': '156643',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M02',
  'periodName': 'February',
  'value': '156644',
  'footnotes': [{}]},
 {'year': '2015',
  'period': 'M01',
  'periodName': 'January',
  'value': '157030',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2014',
  'period': 'M12',
  'periodName': 'December',
  'value': '156332',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M11',
  'periodName': 'November',
  'value': '156494',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M10',
  'periodName': 'October',
  'value': '156417',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M09',
  'periodName': 'September',
  'value': '156040',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M08',
  'periodName': 'August',
  'value': '156130',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M07',
  'periodName': 'July',
  'value': '156007',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M06',
  'periodName': 'June',
  'value': '155707',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M05',
  'periodName': 'May',
  'value': '155684',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M04',
  'periodName': 'April',
  'value': '155369',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M03',
  'periodName': 'March',
  'value': '156028',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M02',
  'periodName': 'February',
  'value': '155483',
  'footnotes': [{}]},
 {'year': '2014',
  'period': 'M01',
  'periodName': 'January',
  'value': '155352',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2013',
  'period': 'M12',
  'periodName': 'December',
  'value': '155182',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M11',
  'periodName': 'November',
  'value': '155265',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M10',
  'periodName': 'October',
  'value': '154673',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M09',
  'periodName': 'September',
  'value': '155687',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M08',
  'periodName': 'August',
  'value': '155605',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M07',
  'periodName': 'July',
  'value': '155599',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M06',
  'periodName': 'June',
  'value': '155749',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M05',
  'periodName': 'May',
  'value': '155536',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M04',
  'periodName': 'April',
  'value': '155394',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M03',
  'periodName': 'March',
  'value': '155005',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M02',
  'periodName': 'February',
  'value': '155312',
  'footnotes': [{}]},
 {'year': '2013',
  'period': 'M01',
  'periodName': 'January',
  'value': '155763',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]},
 {'year': '2012',
  'period': 'M12',
  'periodName': 'December',
  'value': '155628',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M11',
  'periodName': 'November',
  'value': '155338',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M10',
  'periodName': 'October',
  'value': '155554',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M09',
  'periodName': 'September',
  'value': '155160',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M08',
  'periodName': 'August',
  'value': '154763',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M07',
  'periodName': 'July',
  'value': '154948',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M06',
  'periodName': 'June',
  'value': '155083',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M05',
  'periodName': 'May',
  'value': '154866',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M04',
  'periodName': 'April',
  'value': '154545',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M03',
  'periodName': 'March',
  'value': '154749',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M02',
  'periodName': 'February',
  'value': '154671',
  'footnotes': [{}]},
 {'year': '2012',
  'period': 'M01',
  'periodName': 'January',
  'value': '154381',
  'footnotes': [{'code': '1',
    'text': 'Data affected by changes in population controls.'}]}]

In [11]:
df = pd.DataFrame(columns=[
    'series_title', 'series_id', 'seasonality', 'survey_name', 'survey_abbreviation', 'measure_data_type', 'year',
    'period', 'period_name', 'value'
                          ])

In [13]:
for series in json_data['Results']['series']:
    series_title = series['catalog']['series_title']
    series_id = series['catalog']['series_id']
    seasonality = series['catalog']['seasonality']
    survey_name = series['catalog']['survey_name']
    survey_abbreviation = series['catalog']['survey_abbreviation']
    measure_data_type = series['catalog']['measure_data_type']
    for data in series['data']:
        year = data['year']
        period = data['period']
        period_name = data['periodName']
        value = data['value']
        
        #save data in dataframe
        df = pd.concat([df, pd.DataFrame.from_records([{
            'series_title': series_title
            , 'series_id': series_id
            , 'seasonality': seasonality
            , 'survey_name': survey_name
            , 'survey_abbreviation': survey_abbreviation
            , 'measure_data_type': measure_data_type
            , 'year': year
            , 'period': period
            , 'period_name': period_name
            , 'value': value
        }])], ignore_index=True)

In [14]:
df

,series_title,series_id,seasonality,survey_name,survey_abbreviation,measure_data_type,year,period,period_name,value,demographic_age
0,(Seas) Civilian Labor Force Level,LNS11000000,Seasonally Adjusted,Labor Force Statistics from the Current Popula...,LN,Number in thousands,2022,M12,December,164966,16 years and over
1,(Seas) Civilian Labor Force Level,LNS11000000,Seasonally Adjusted,Labor Force Statistics from the Current Popula...,LN,Number in thousands,2022,M11,November,164527,16 years and over
2,(Seas) Civilian Labor Force Level,LNS11000000,Seasonally Adjusted,Labor Force Statistics from the Current Popula...,LN,Number in thousands,2022,M10,October,164646,16 years and over
3,(Seas) Civilian Labor Force Level,LNS11000000,Seasonally Adjusted,Labor Force Statistics from the Current Popula...,LN,Number in thousands,2022,M09,September,164619,16 years and over
4,(Seas) Civilian Labor Force Level,LNS11000000,Seasonally Adjusted,Labor Force Statistics from the Current Popula...,LN,Number in thousands,2022,M08,August,164714,16 years and over
...,...,...,...,...,...,...,...,...,...,...,...
1315,"Average hourly earnings of all employees, tota...",CES0500000003,Seasonally Adjusted,"Employment, Hours, and Earnings from the Curre...",CE,AVERAGE HOURLY EARNINGS OF ALL EMPLOYEES,2012,M05,May,23.39,NaN
1316,"Average hourly earnings of all employees, tota...",CES0500000003,Seasonally Adjusted,"Employment, Hours, and Earnings from the Curre...",CE,AVERAGE HOURLY EARNINGS OF ALL EMPLOYEES,2012,M04,April,23.39,NaN
1317,"Average hourly earnings of all employees, tota...",CES0500000003,Seasonally Adjusted,"Employment, Hours, and Earnings from the Curre...",CE,AVERAGE HOURLY EARNINGS OF ALL EMPLOYEES,2012,M03,March,23.36,NaN
1318,"Average hourly earnings of all employees, tota...",CES0500000003,Seasonally Adjusted,"Employment, Hours, and Earnings from the Curre...",CE,AVERAGE HOURLY EARNINGS OF ALL EMPLOYEES,2012,M02,February,23.27,NaN
1319,"Average hourly earnings of all employees, tota...",CES0500000003,Seasonally Adjusted,"Employment, Hours, and Earnings from the Curre...",CE,AVERAGE HOURLY EARNINGS OF ALL EMPLOYEES,2012,M01,January,23.24,NaN